### ISSUE TITLE
Why does K-cores performe better than IMM at Digg?

### ISSUE THREAD

**Issue by FeiGSSS** [GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning#1]
You wrote in the Results that "with the exception of K-core that surpasses IMM at Digg".  
Do you have any ideas about why this can happen?

**Comment by geopanag** [comment]
There can be a number of factors.
IMM is developed focusing more on scalability and its usefulness with smaller networks is unclear yet. For example, in the experiments of the original IMM paper the algorithm has similar expected influence as a heuristic method like SIMPATH in a small network like NetHEPT. Digg is significantly smaller than Weibo and MAG CS, and k-core might indeed detect better influencers in the core of the network.
Moreover, IMM relies on e, which we set to 0.1. Had we tune it more, maybe it could surpass it, but we perform no parameter tuning on both IMM and IMINFECTOR.
Finally DNI is not the traditional evaluation based on simulations over the network, so the comparison becomes more complex and one needs to take into account the actual diffusions to explain it.

**Comment by FeiGSSS** [comment]
Thanks for your reply
