### ISSUE TITLE
Problems of MAG Computer Science

### ISSUE THREAD

**Issue by mumaba** [GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning#12]
Hi, I really enjoyed your research, it was a real eye-opener and inspired me a lot. But I have a little problem with the MAG Computer Science dataset, I can't handle this very well. Can you share MAG Computer Science with me? Thank you.

**Comment by geopanag** [comment]
Hi, unfortunately we had to make a data license agreement  with MAG so we can not share it directly. However, you can find the data with a few differences in https://www.microsoft.com/en-us/research/project/open-academic-graph/ and recreate a similar dataset.

**Comment by mumaba** [comment]
ok. thank you very much
