### ISSUE TITLE
cannot download dataset

### ISSUE THREAD

**Issue by red0206** [GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning#22]
Opening the download addresses of the Sina Weibo and MAG datasets both show errors. Could you re-share the Sina Weibo and MAG datasets? Thank you very much!!!

**Comment by geopanag** [comment]
Hello, you can get a processed version of the weibo dataset here: https://drive.google.com/drive/folders/1qXXXNpI2qT9Jcv51n7yq9912YGNTmYVA?usp=sharing
Unfortunately we cannot distribute MAG.
