### ISSUE TITLE
 What is variable "our_set"  in the file "extract_feats_and_trainset.py"

### ISSUE THREAD

**Issue by calebauyang** [GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning#3]
Firstly, thanks for your share! There is a question about the code "store_samples(fn,cascade_nodes,cascade_times,initiators,op_time,our_set)" in the file "extract_feats_and_trainset.py". What is "our_set"? No value assigned to the variable  "our_set".

**Comment by geopanag** [comment]
Thank you for catching this, it is the file we write the train set at. I fixed it.

**Comment by calebauyang** [comment]
i see. thanks for your answer.

**Comment by calebauyang** [comment]
i see. thanks for your answer.
