### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by calebauyang** [GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning#4]
I am very happy to receive your answer you did before in Github. Thanks! I have some other questions in the attached file.
[some questions about the code. Thanks!.docx](https://github.com/GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning/files/3775981/some.questions.about.the.code.Thanks.docx)

**Comment by geopanag** [comment]
Thank you for your valuable questions. PFA the answers. 

[answers.docx](https://github.com/GiorgosPanagopoulos/Influence-Maximization-via-Representation-Learning/files/3779788/answers.docx)

**Comment by calebauyang** [comment]
thanks for your answers.
